"""create maternity schema
Revision ID: maternite_0001
Revises:
"""
from alembic import op
import sqlalchemy as sa
revision='maternite_0001'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('pregnancies',
        sa.Column('id',sa.String(36),primary_key=True),sa.Column('pregnancy_number',sa.String(60),nullable=False),sa.Column('patient_id',sa.String(36),nullable=False),sa.Column('active_patient_key',sa.String(36),nullable=True),sa.Column('consultation_id',sa.String(36),nullable=True),sa.Column('gravida',sa.Integer(),nullable=False),sa.Column('para',sa.Integer(),nullable=False),sa.Column('lmp_date',sa.String(10),nullable=True),sa.Column('edd',sa.String(10),nullable=True),sa.Column('risk_level',sa.String(20),nullable=False),sa.Column('risk_factors',sa.Text(),nullable=True),sa.Column('referral_reason',sa.Text(),nullable=True),sa.Column('status',sa.String(20),nullable=False),sa.Column('correlation_id',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('created_by',sa.String(36),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.Column('labor_admitted_at',sa.DateTime(),nullable=True),sa.Column('labor_admit_key',sa.String(160),nullable=True),sa.UniqueConstraint('pregnancy_number',name='uq_pregnancy_number'),sa.UniqueConstraint('active_patient_key',name='uq_active_patient_key'),sa.UniqueConstraint('idempotency_key',name='uq_pregnancy_idempotency'),sa.UniqueConstraint('labor_admit_key',name='uq_pregnancy_labor_admit_key'))
    for c in ['pregnancy_number','patient_id','active_patient_key','consultation_id','status','correlation_id','idempotency_key','created_by']: op.create_index(f'ix_pregnancies_{c}','pregnancies',[c])
    op.create_table('prenatal_visits',sa.Column('id',sa.String(36),primary_key=True),sa.Column('pregnancy_id',sa.String(36),sa.ForeignKey('pregnancies.id',ondelete='CASCADE'),nullable=False),sa.Column('visit_at',sa.DateTime(),nullable=False),sa.Column('gestational_age_weeks',sa.Integer(),nullable=False),sa.Column('observations',sa.Text(),nullable=True),sa.Column('systolic_bp',sa.Integer(),nullable=False),sa.Column('diastolic_bp',sa.Integer(),nullable=False),sa.Column('weight_kg_x100',sa.Integer(),nullable=False),sa.Column('fetal_heart_bpm',sa.Integer(),nullable=False),sa.Column('recorded_by',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.UniqueConstraint('idempotency_key',name='uq_prenatal_idempotency'))
    for c in ['pregnancy_id','visit_at','recorded_by','idempotency_key']: op.create_index(f'ix_prenatal_visits_{c}','prenatal_visits',[c])
    op.create_table('labor_events',sa.Column('id',sa.String(36),primary_key=True),sa.Column('pregnancy_id',sa.String(36),sa.ForeignKey('pregnancies.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.String(30),nullable=False),sa.Column('event_at',sa.DateTime(),nullable=False),sa.Column('description',sa.Text(),nullable=True),sa.Column('cervical_dilation_x10',sa.Integer(),nullable=False),sa.Column('fetal_heart_bpm',sa.Integer(),nullable=False),sa.Column('recorded_by',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.UniqueConstraint('idempotency_key',name='uq_labor_event_idempotency'))
    for c in ['pregnancy_id','event_type','event_at','recorded_by','idempotency_key']: op.create_index(f'ix_labor_events_{c}','labor_events',[c])
    op.create_table('deliveries',sa.Column('id',sa.String(36),primary_key=True),sa.Column('delivery_number',sa.String(60),nullable=False),sa.Column('pregnancy_id',sa.String(36),sa.ForeignKey('pregnancies.id',ondelete='RESTRICT'),nullable=False),sa.Column('patient_id',sa.String(36),nullable=False),sa.Column('delivered_at',sa.DateTime(),nullable=False),sa.Column('mode',sa.String(30),nullable=False),sa.Column('outcome',sa.String(30),nullable=False),sa.Column('complications',sa.Text(),nullable=True),sa.Column('attendant_id',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('billing_status',sa.String(30),nullable=False),sa.Column('billing_charge_id',sa.String(36),nullable=True),sa.Column('billed_amount_minor',sa.Integer(),nullable=False),sa.Column('currency_code',sa.String(3),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('delivery_number',name='uq_delivery_number'),sa.UniqueConstraint('idempotency_key',name='uq_delivery_idempotency'))
    for c in ['delivery_number','pregnancy_id','patient_id','delivered_at','attendant_id','idempotency_key','billing_status']: op.create_index(f'ix_deliveries_{c}','deliveries',[c])
    op.create_table('newborns',sa.Column('id',sa.String(36),primary_key=True),sa.Column('newborn_number',sa.String(60),nullable=False),sa.Column('delivery_id',sa.String(36),sa.ForeignKey('deliveries.id',ondelete='CASCADE'),nullable=False),sa.Column('mother_patient_id',sa.String(36),nullable=False),sa.Column('sex',sa.String(20),nullable=False),sa.Column('weight_g',sa.Integer(),nullable=False),sa.Column('apgar_1',sa.Integer(),nullable=False),sa.Column('apgar_5',sa.Integer(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('registered_by',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('newborn_number',name='uq_newborn_number'),sa.UniqueConstraint('idempotency_key',name='uq_newborn_idempotency'))
    for c in ['newborn_number','delivery_id','mother_patient_id','registered_by','idempotency_key']: op.create_index(f'ix_newborns_{c}','newborns',[c])
    op.create_table('billing_outbox',sa.Column('id',sa.String(36),primary_key=True),sa.Column('delivery_id',sa.String(36),nullable=False),sa.Column('patient_id',sa.String(36),nullable=False),sa.Column('amount_minor',sa.Integer(),nullable=False),sa.Column('currency_code',sa.String(3),nullable=False),sa.Column('correlation_id',sa.String(36),nullable=False),sa.Column('idempotency_key',sa.String(160),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('billing_charge_id',sa.String(36),nullable=True),sa.Column('last_error',sa.Text(),nullable=True),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False),sa.UniqueConstraint('delivery_id',name='uq_maternity_billing_delivery'),sa.UniqueConstraint('idempotency_key',name='uq_maternity_billing_idempotency'))
    for c in ['delivery_id','patient_id','correlation_id','idempotency_key','status']: op.create_index(f'ix_billing_outbox_{c}','billing_outbox',[c])
def downgrade():
    op.drop_table('billing_outbox'); op.drop_table('newborns'); op.drop_table('deliveries'); op.drop_table('labor_events'); op.drop_table('prenatal_visits'); op.drop_table('pregnancies')
